### ISSUE TITLE
Deprecate `Context::declare` or `Context::declare_const`

### ISSUE THREAD

**Issue by rachitnigam** [elliottt/easy-smt#15]
The `Context` has both a [`declare`](https://docs.rs/easy-smt/latest/easy_smt/struct.Context.html#method.declare) method, which dispatches to [`declare_fun`](https://docs.rs/easy-smt/latest/easy_smt/struct.Context.html#method.declare_fun), and a [`declare_const`](https://docs.rs/easy-smt/latest/easy_smt/struct.Context.html#method.declare_const) method, which uses the SMTLIB `declare-const` construct. However, `declare-const` in SMTLIB is defined to be a macro for `define-fun` in the same way that `declare` is implemented (See [Z3 reference](https://microsoft.github.io/z3guide/docs/logic/Uninterpreted-functions-and-constants)). Because of this, we should probably only expose one of these methods on the context and deprecate the other.

**Comment by fitzgen** [comment]
After digging in some more, I now realize that `Context::declare` doesn't directly correspond to any SMTLIB form, while `Context::declare_const` corresponds to the SMTLIB `declare-const`. Since `Context::declare` and `Context::declare_const` are the same, as you pointed out, I think it makes sense to remove/deprecate `Context::declare` and only keep `Context::declare_const`.

Would you like to send a PR doing the above?

Thanks for filing this issue.

**Comment by rachitnigam** [comment]
Sure, I can do that!
